# Generated by Django 5.0.7 on 2024-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('publishdate', models.DateField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('started_reading', models.DateField(max_length=100)),
                ('ended_reading', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
