# Generated by Django 5.0.7 on 2024-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishdate',
            field=models.DateField(default='No publish date available', max_length=100),
        ),
    ]
