# Generated by Django 5.0.7 on 2024-07-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_book_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='userid',
        ),
    ]
