# Generated by Django 5.0.7 on 2024-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0004_rename_user_id_book_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ended_reading',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
