# Generated by Django 5.0.7 on 2024-07-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0007_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='static/userimgs/'),
        ),
    ]
