# Generated by Django 5.0.7 on 2024-07-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0009_alter_user_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilepic',
        ),
    ]
